{
  "comments": [
    {
      "key": {
        "uuid": "1f97d178_b4ac749e",
        "filename": "/COMMIT_MSG",
        "patchSetId": 5
      },
      "lineNbr": 12,
      "author": {
        "id": 1174470
      },
      "writtenOn": "2018-01-19T18:47:11Z",
      "side": 1,
      "message": "I think the description should explain further why the destructor is called twice.",
      "range": {
        "startLine": 11,
        "startChar": 18,
        "endLine": 12,
        "endChar": 17
      },
      "revId": "c79939be7bf5e80af7f46a00dcd90fcfbc30935b",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}